[package]
name = "rust-myip"
version = "0.1.0"
authors = ["Brice Theurillat <brice.theurillat@protonmail.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.6"